import { FindingInput, normalizeFindings } from "./findings";

export interface ReportData {
  fileName: string;
  riskScore: number;
  findings: FindingInput[];
  timestamp: string;
}

export interface CompanyVerification {
  companyName: string;
  country: string;
  verificationStatus: "verified" | "pending" | "failed";
  riskLevel: "high" | "low";
  registrationFound: boolean;
  timestamp: string;
}

export const generateReport = async (data: ReportData): Promise<Blob> => {
  const normalizedFindings = normalizeFindings(data.findings);

  // Dynamically import jsPDF to keep it client-side only
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  // ── Header ──────────────────────────────────────────────────────────────────
  doc.setFillColor(15, 23, 42); // slate-950
  doc.rect(0, 0, pageWidth, 40, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text("TradeSecurix", margin, 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text("Fraud Detection & Trade Document Verification", margin, 26);

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(
    `Generated: ${new Date(data.timestamp).toLocaleString("en-US", {
      dateStyle: "long",
      timeStyle: "short",
    })}`,
    pageWidth - margin,
    26,
    { align: "right" }
  );

  y = 52;

  // ── Title: Executive Summary ─────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(15, 23, 42);
  doc.text("Risk Assessment Report", margin, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  doc.text(
    "This document constitutes an executive-level fraud risk assessment " +
      "generated by TradeSecurix automated analysis.",
    margin,
    y,
    { maxWidth: contentWidth }
  );
  y += 14;

  // ── Divider ──────────────────────────────────────────────────────────────────
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // ── Document Info ────────────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("1. Document Information", margin, y);
  y += 7;

  const infoRows = [
    ["File name", data.fileName],
    ["Analysis date", new Date(data.timestamp).toLocaleString()],
  ];
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  for (const [key, val] of infoRows) {
    doc.setTextColor(71, 85, 105);
    doc.text(key + ":", margin, y);
    doc.setTextColor(15, 23, 42);
    doc.text(String(val), margin + 40, y);
    y += 7;
  }
  y += 4;

  // ── Risk Score ────────────────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("2. Risk Score", margin, y);
  y += 8;

  const riskColor =
    data.riskScore < 25
      ? [16, 185, 129] // green
      : data.riskScore < 50
      ? [245, 158, 11] // amber
      : data.riskScore < 75
      ? [249, 115, 22] // orange
      : [239, 68, 68]; // red

  doc.setFillColor(...(riskColor as [number, number, number]));
  doc.roundedRect(margin, y, 60, 18, 3, 3, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text(`${data.riskScore}/100`, margin + 6, y + 12);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  const riskLabel = formatRiskScore(data.riskScore);
  doc.text(riskLabel, margin + 66, y + 12);
  y += 28;

  // ── Findings ─────────────────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("3. Findings", margin, y);
  y += 8;

  for (const finding of normalizedFindings) {
    const severityColor: [number, number, number] =
      finding.severity === "high"
        ? [239, 68, 68]
        : finding.severity === "medium"
        ? [245, 158, 11]
        : [16, 185, 129];

    doc.setFillColor(...severityColor);
    doc.circle(margin + 2, y - 1.5, 2, "F");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    const lines = doc.splitTextToSize(finding.message, contentWidth - 10) as string[];
    doc.text(lines, margin + 8, y);
    y += lines.length * 6 + 3;

    if (y > 260) {
      doc.addPage();
      y = 20;
    }
  }
  y += 4;

  // ── Recommendation ────────────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("4. Recommendation", margin, y);
  y += 7;

  const recommendation =
    data.riskScore < 25
      ? "Document analysis is consistent with standard trade practices. No immediate action required."
      : data.riskScore < 50
      ? "Exercise elevated due diligence. Request additional supporting documents from the counterparty before proceeding."
      : data.riskScore < 75
      ? "Multiple risk signals detected. Do not proceed without independent verification. Escalate to compliance team."
      : "CRITICAL RISK: High probability of fraud or document manipulation. Halt transaction immediately and report to compliance.";

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  const recLines = doc.splitTextToSize(recommendation, contentWidth) as string[];
  doc.text(recLines, margin, y);
  y += recLines.length * 6 + 10;

  // ── Footer ────────────────────────────────────────────────────────────────────
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, pageHeight - 18, pageWidth - margin, pageHeight - 18);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184);
    doc.text(
      "This report is generated by TradeSecurix and is for internal use only. Not for external distribution.",
      margin,
      pageHeight - 12
    );
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 12, {
      align: "right",
    });
  }

  return doc.output("blob");
};

export const generateReportPDF = generateReport;

export const formatRiskScore = (score: number): string => {
  if (score < 25) return "Low Risk";
  if (score < 50) return "Medium Risk";
  if (score < 75) return "High Risk";
  return "Critical Risk";
};

export const getRiskColor = (score: number): string => {
  if (score < 25) return "bg-emerald-500/15 text-emerald-300";
  if (score < 50) return "bg-amber-500/15 text-amber-300";
  if (score < 75) return "bg-orange-500/15 text-orange-300";
  return "bg-red-500/15 text-red-300";
};

